"""Version constants shared by the Complete build and protocol handshakes."""

COMPLETE_VERSION = "1.0.2"
WORKER_API_VERSION = 2
JOB_SCHEMA_VERSION = 2
SESSION_SCHEMA_VERSION = 2
FLOW_SCHEMA_VERSION = 1
SESSION_SCHEMA_V2_VERSION = 2
FLOW_SCHEMA_V2_VERSION = 2
PCAP_INDEX_SCHEMA_VERSION = 1
BATCH_MANIFEST_SCHEMA_VERSION = 1
MIHOMO_TRACING_API_VERSION = 1
MIHOMO_EVENT_SCHEMA_VERSION = 1
